.PHONY: clean All

All:
	@echo "----------Building project:[ NativeTools - Debug ]----------"
	@cd "NativeTools" && "$(MAKE)" -f  "NativeTools.mk"
clean:
	@echo "----------Cleaning project:[ NativeTools - Debug ]----------"
	@cd "NativeTools" && "$(MAKE)" -f  "NativeTools.mk" clean
