/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeToolsX11 */

#ifndef _Included_NativeToolsX11
#define _Included_NativeToolsX11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeToolsX11
 * Method:    set_parent_gtk
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_NativeToolsX11_set_1parent_1gtk
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     NativeToolsX11
 * Method:    move_resize_window
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_NativeToolsX11_move_1resize_1window
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
